"""Insurance configuration constants.

Central place for all insurance-specific constants.
No AIOS imports — pure business config.
"""

from __future__ import annotations

# Marking constants
MARKING_PII = "PII"
MARKING_FINANCIAL = "FINANCIAL"
MARKING_RESTRICTED = "RESTRICTED"
MARKING_CLAIMS = "CLAIMS"
MARKING_MANAGEMENT = "MANAGEMENT"

# Agent thresholds
TRIAGE_URGENT_THRESHOLD = 50_000
TRIAGE_HIGH_THRESHOLD = 25_000
TRIAGE_MEDIUM_THRESHOLD = 5_000
FRAUD_HIGH_VALUE_THRESHOLD = 100_000
FRAUD_PROXIMITY_DAYS = 30
FRAUD_MULTI_CLAIM_DAYS = 90

# Adjuster assignments
URGENT_BODILY_INJURY_ADJUSTER = "senior-adjuster-garcia"

# Deployment
CANARY_BAKE_MINUTES = 120
STAGING_BAKE_MINUTES = 240
PRODUCTION_BAKE_MINUTES = 360
MAINTENANCE_WINDOW_START = 2  # UTC
MAINTENANCE_WINDOW_END = 5  # UTC
